---
# Running the 5GTANGO API Gateway (Docker container)
- debug: msg="##### 5GTANGO API-GTW DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: run the 5GTANGO Security Gateway
  docker_container:
    name: "tng-api-gtw"
    image: "{{ repository }}/tng-api-gtw:{{ version }}"
    state: started
    recreate: yes
    pull: true
    restart_policy: "always"
    network_mode: bridge
    log_driver: gelf
    log_options: gelf-address=udp://10.30.0.219:12900
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - tng-api-gtw
    published_ports:
      - "32002:5000"

