---
# Running the Sonata Catalogue (Docker container)
- debug: msg="##### SP Catalogue DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
- name: deploy Catalogues as a Docker container (from the Registry to the SP VM appliance)
  docker_container:
    name: son-catalogue-repos
    image: "{{ repository }}/son-catalogue-repos:{{ version }}"
    state: started
    recreate: yes
    pull: true
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-catalogue-repos
    dns_servers: "8.8.8.8"
    published_ports: "4002:4011"
